name: DIY Bolt Dev Server

on:
  push:
    branches: [ "ghaction" ]
  workflow_dispatch:

jobs:
  run-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Start dev server and expose with localtunnel
      run: |
        pnpm run dev &
        ssh -R 80:localhost:5173 serveo.net
